# Author: Afaq Ahemd <afaq.ahmed@xgrid.co>

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/ui-${BRANCH_NAME}:${SHORT_SHA}'
      - './app'
    id: 'Build Docker Image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/ui-${BRANCH_NAME}:${SHORT_SHA}'
    id: 'Push to Artifact Registry'

images:
  - 'us-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/ui-${BRANCH_NAME}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY