steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Project ID: " $_PROJECT_ID
        echo "Container Tag: " $_CONTAINER_TAG

        gcloud config set project $_PROJECT_ID
        gcloud run deploy afaq-cloudrun-service --image us-east1-docker.pkg.dev/${_PROJECT_ID}/afaq-docker-repo/ui-$_CONTAINER_TAG' --region us-east1
    id: 'Deploy ui app'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _PROJECT_ID: $(body.project_id)
    _CONTAINER_TAG: $(body.artifact)